flows:
  - budidaya/kimia/*
  - budidaya/panen/*
  - budidaya/perlakuan/*
  - budidaya/sampling/*
excludeTags:
  - login
executionOrder:
    continueOnFailure: false
    flowsOrder:
        - AT32
        - AT33
        - AT34
        - AT35
        - AT36
        - AT37
        - AT38
        - AT39
        - AT40
        - AT44
        - AT45
        - AT46
