flows:
  - budidaya/kimia/*
  
excludeTags:
  - login
  - ATPERLAKUAN
  - ATPANEN
  - ATSAMPLING
  - ATMIKROBIOLOGI
  
executionOrder:
    continueOnFailure: false
    flowsOrder:
        - AT44CRUD
        
